import '@/web/styles/global.css';

export const metadata = {
  description: 'Generated by Next.js',
  title: 'Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-white font-sans text-slate-900 antialiased" lang="en">
      <head />
      <body className="min-h-screen">{children}</body>
    </html>
  );
}
