import { Inter } from 'next/font/google';
import '@/web/styles/global.css';

export const metadata = {
  description: 'Generated by Next.js',
  title: 'Next.js',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-white font-sans text-slate-900 antialiased" lang="en">
      <head />
      <body className={`min-h-screen ${inter.className}`}>{children}</body>
    </html>
  );
}
